/*

      File:  Deck.java

      Programmer:  Viacheslav Burmistrov

      Purpose: The Deck class acts as a deck to where to cards go to. It creates
      a deck of 52 cards, which can be shuffled with Shuffle method any number of times.
      It can return a card depending on the variable passed into the return method.

      I affirm that this program is entirely my own work and none of it is the work of anyone else.

 */
package assignment_2_slava;

import java.util.Random;

/**
 * The Deck class acts as a deck to where to cards go to. It creates a deck of
 * 52 cards, which can be shuffled with Shuffle method any number of times. It
 * can return a card depending on the variable passed into the return method.
 *
 */
public class Deck {

    Random ranGen = new Random();
    Card[] DeckArray; //An array where the cards will be stored
    private Card temp1; //variable used to store temperatry card to shuffle the deck
    private int rand; //Stores random number that will be generated 
    private final int DECK_SIZE; //Stores the deck size

    /**
     * Creates a deck of 52 cards by intializing the deck array with 52 objects
     * of the Card type. Each object is ran through a loop that parses a rank
     * and a suit, generated by a 'for' loop.
     */
    public Deck() {//Generates a Deck of 52 cards when called
        DECK_SIZE = 52;
        DeckArray = new Card[DECK_SIZE];

        for (int j = 0; j < 4; j++) {
            for (int k = 2; k < 15; k++) {
                Card card = new Card(k, j);
                DeckArray[(k - 2) + (j * 13)] = card;
            }
        }
    }

    /**
     * Shuffles the deck of cards by taking a card and putting it in the random
     * spot in the deck. The deck is shifted to the correct position to fill the
     * whole left by the card.
     */
    public void Shuffle() {
        for (int i = 0; i < DECK_SIZE; i++) { //Each card is shuffled at least ones
            temp1 = DeckArray[i]; //"Remove the card"
            rand = ranGen.nextInt(DECK_SIZE); //Find to place to put it
            if (rand >= i) { //if the random # is bigger then card postion #
                for (int j = i; j < rand; j++) { //Shifts the cards to the left
                    DeckArray[j] = DeckArray[j + 1];
                }
            } else { //if postion # is greater then random #
                for (int k = i; k > rand; k--) { //Shifts the cards to the right
                    DeckArray[k] = DeckArray[k - 1];
                }
            }
            DeckArray[rand] = temp1; //Places the card in the random place
        }
    }

    /**
     *
     * Returns the card from the called position of the deck.
     *
     * @param x the position from where the card will be returned.
     * @return card object.
     */
    public Card GetTopCard(int x) {
        return DeckArray[x];
    }

}
